import type { Metadata } from "next";
import "./globals.css";
// import { Averia_Libre, Poppins } from "next/font/google";
import { Poppins } from "next/font/google";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const averia_Libre = Averia_Libre({
//   weight: ["400", "700"],
//   subsets: ["latin"],
// });
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children?: React.ReactNode;
  params?: Promise<{ locale: string }>;
}>) {
  const { locale } = (await params) || {};
  if (!locale || !routing.locales.includes(locale as "en" | "no")) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`antialiased ${poppins.className}`}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
